### ISSUE TITLE
Failed of missing module 'log4js'

### ISSUE THREAD

**Issue by charlesdeng** [samcodex/ngarch-app#1]
$ npm start

> ngarch-app@1.0.0 start C:\Users\admin\git\github\ngarch-app
> node node_modules/ngarch-server/server

module.js:471
    throw err;
    ^

Error: Cannot find module 'log4js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at req (C:\Users\admin\git\github\ngarch-app\node_modules\amdefine\amdefine.js:144:31)
    at stringRequire (C:\Users\admin\git\github\ngarch-app\node_modules\amdefine\amdefine.js:220:28)
    at amdRequire (C:\Users\admin\git\github\ngarch-app\node_modules\amdefine\amdefine.js:113:24)
    at Object.<anonymous> (C:\Users\admin\git\github\ngarch-app\node_modules\ngarch-server\server.js:6:350)
    at runFactory (C:\Users\admin\git\github\ngarch-app\node_modules\amdefine\amdefine.js:183:30)
    at stringRequire (C:\Users\admin\git\github\ngarch-app\node_modules\amdefine\amdefine.js:216:28)
    at amdRequire (C:\Users\admin\git\github\ngarch-app\node_modules\amdefine\amdefine.js:113:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngarch-app@1.0.0 start: `node node_modules/ngarch-server/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ngarch-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by samcodex** [comment]
Fixed
